Home-Page Subscription Form Upgrades
audioverse-org/audioverse-next pull request #531
Opened 2024-05-09 20:51 UTC by jperegrino75

Made the following changes to subscription form on audioverse.org Home page:

1. Added new verbiage to the Newsletter form
2. added two checkboxes: newsLetter and Weekly pics
3. integrated to Active Campaign

https://audioverse7.atlassian.net/browse/AV-940

2024-05-22 15:26 UTC, alangumer requested changes
Great job, just fix the small things that I mentioned.

2024-05-22 15:26 UTC, alangumer commented on src/components/molecules/newsletterForm.tsx
> +								defaultMessage="Newsletter typically about once a month"
Use parentheses or another separator to specify the frequency.

2024-05-22 15:26 UTC, alangumer commented on src/components/molecules/newsletterForm.tsx
> +								defaultMessage="Weekly Picks goes out every Monday"
Same here.

2024-05-23 15:06 UTC, jperegrino75 commented on src/components/molecules/newsletterForm.tsx
> +								defaultMessage="Newsletter typically about once a month"
done

2024-05-23 21:51 UTC, alangumer approved these changes

2024-05-29 18:51 UTC, merged