Av 1026 add sermon to playlist website
audioverse-org/audioverse-next pull request #533
Opened 2024-05-29 00:26 UTC by okeinom

https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-1026

2024-05-29 20:09 UTC, closed without merging

2024-05-29 21:36 UTC, alangumer requested changes

2024-05-29 21:36 UTC, alangumer commented on src/components/molecules/teaseRecording.tsx
> +					<Link
Use a modal instead of navigating to a new page, this would allow to keep the current state.

2024-05-29 21:36 UTC, alangumer commented on src/pages/[language]/playlists/new/index.tsx
> +			const data = await playlistAdd<PlaylistAddMutationVariables>({
Set is loading to true.

2024-05-29 21:36 UTC, alangumer commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +}: //onDelete,
Remove comment.

2024-05-29 21:36 UTC, alangumer commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +	//const refTitle = useRef<HTMLInputElement>(null);
Same here.

2024-05-29 21:36 UTC, alangumer commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +					defaultMessage: 'Tile',
Typo.

2024-05-29 21:36 UTC, alangumer commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +				//onSubmitEditing={() => refDescription.current?.focus()}
Remove comment.

2024-05-29 21:36 UTC, alangumer commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +					<DisclosureIcon color={BaseColors.DARK} />
This is being displayed bellow and not to the side.

2024-05-29 21:36 UTC, alangumer commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +					<Link
This shouldn't be a link.

2024-05-29 21:36 UTC, alangumer commented on src/pages/[language]/playlists/Playlistform.module.css
> +	background-color: #ffffff; /* Replace COLORS.WHITE with actual color value */
Use the values from the variables.

2024-05-29 21:36 UTC, alangumer commented on src/pages/[language]/playlists/Playlistform.module.css
> +	border-width: 1px;
Same here.

2024-05-29 21:36 UTC, alangumer commented on src/pages/[language]/playlists/Playlistform.module.css
> +	background-color: #f0f0f0; /* Replace COLORS_DARKENED.WHITE with actual color value */
Same here.

2024-05-29 21:36 UTC, alangumer commented on src/pages/_app.tsx
> +import '../styles/loader.scss';
Remove it from here and add it where it's used.

2024-05-30 13:56 UTC, okeinom commented on src/components/constants/Loader.tsx
> +const Loader: React.FC = () => {
done

2024-05-30 14:02 UTC, okeinom commented on src/components/molecules/teaseRecording.tsx
> +	//<FormattedMessage id="add_to_playlist_bnt" defaultMessage="Playlist" />;
done

2024-05-30 14:09 UTC, okeinom commented on src/components/molecules/teaseRecording.tsx
> +				hideClose={true}
kk

2024-05-30 14:25 UTC, okeinom commented on src/containers/library/playlist/detail.tsx
> +						defaultMessage="NOT SHAREABLE"
Updated

2024-05-30 14:26 UTC, okeinom commented on src/containers/library/playlist/detail.tsx
> +					defaultMessage="This Playlist is Private. Only SHAREABLE Playlists can be shared."
This is the msg John placed on the story

2024-05-30 14:44 UTC, okeinom commented on src/components/atoms/Loader.tsx
> +//import '../../styles/loader.scss';
kk

2024-05-30 15:48 UTC, okeinom commented on src/pages/_app.tsx
> +import '../styles/loader.scss';
done

2024-05-30 15:48 UTC, okeinom commented on src/styles/loader.scss
> +@keyframes shine {
done

2024-05-30 20:26 UTC, alangumer commented on src/components/molecules/teaseRecording.tsx
> +		id: 'dd_to_playlist_bnt',
Also bnt is misspelled.

2024-05-30 20:31 UTC, alangumer commented on src/containers/library/playlist/detail.tsx
> +					defaultMessage="This Playlist is Private. Only SHAREABLE Playlists can be shared."
Yes, but the app is using a different one.

2024-05-30 20:33 UTC, alangumer commented on src/pages/[language]/playlists/addToPlaylist/PlaylistItem.tsx
> +						<SuccessIcon className={styles.leftIcon} width="24" height="24" />
The item height changes when the item is added to a playlist, and it shouldn't.

2024-05-31 01:51 UTC, okeinom commented on src/components/constants/mutations/useRecordingPlaylist.ts
> +				await queryClient.cancelQueries(PLAYLIST_REFETCH_QUERIES);
Not getting this to work

2024-05-31 01:53 UTC, okeinom commented on src/components/molecules/teaseRecording.tsx
> +		id: 'dd_to_playlist_bnt',
updated

2024-05-31 01:53 UTC, okeinom commented on src/components/constants/mutations/useRecordingPlaylist.ts
> +				if (data?.playlistRecordingAdd) {
need your help with this

2024-05-31 01:55 UTC, okeinom commented on src/containers/library/playlist/detail.tsx
> +					defaultMessage="This Playlist is Private. Only SHAREABLE Playlists can be shared."
updated

2024-05-31 01:56 UTC, okeinom commented on src/pages/[language]/playlists/addToPlaylist/PlaylistList.tsx
> +							defaultMessage="Scroll down for more"
whats not centered

2024-05-31 01:58 UTC, okeinom commented on src/pages/[language]/playlists/addToPlaylist/query.graphql
> +query GetRecordingHasFavorited($id: ID!) {
moved

2024-06-04 14:47 UTC, alangumer commented on src/components/constants/mutations/useRecordingPlaylist.ts
> +				await queryClient.cancelQueries(PLAYLIST_REFETCH_QUERIES);
?

2024-06-04 14:57 UTC, alangumer commented on src/pages/[language]/playlists/addToPlaylist/PlaylistList.tsx
> +							defaultMessage="Scroll down for more"
The message is not centered horizontally.

2024-06-05 17:50 UTC, okeinom commented on src/pages/[language]/playlists/addToPlaylist/PlaylistList.tsx
> +							defaultMessage="Scroll down for more"
updated

2024-06-05 18:24 UTC, okeinom commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +					<Link
updated

2024-06-05 18:25 UTC, okeinom commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +					<Link
updated