Av 1028 update playlist details website
audioverse-org/audioverse-next pull request #534
Opened 2024-05-29 20:18 UTC by okeinom

2024-05-29 20:40 UTC, okeinom commented
https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-1028

2024-05-29 22:05 UTC, alangumer requested changes
I see that this PR has the changes from https://github.com/audioverse-org/audioverse-next/pull/533, so please take that into account as well.

2024-05-30 15:53 UTC, okeinom commented on src/pages/[language]/playlists/[playlist].ts
> -import { GetServerSidePropsContext, GetServerSidePropsResult } from 'next';
added

2024-05-30 15:56 UTC, okeinom commented on src/containers/library/playlist/list.tsx
> +	useEffect(() => {
kk

2024-05-30 15:58 UTC, okeinom commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +								defaultMessage="Delete Playlist"
done

2024-05-30 21:29 UTC, alangumer requested changes

2024-05-30 21:29 UTC, alangumer commented on src/styles/styles.scss
> +	margin-bottom: 1px;
Don't update this because this applies globally, do it at the element level.

2024-05-30 21:29 UTC, alangumer commented on src/components/molecules/teaseRecording.tsx
> +							setIsPlaylistModalOpen(false);
Remove this.

2024-05-30 21:29 UTC, alangumer commented on src/components/molecules/teaseRecording.tsx
> +					<FormattedMessage id="new_playlist" defaultMessage="New playlist" />
The style doesn't match the Figma prototype.

2024-05-30 21:29 UTC, alangumer commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +					<FormattedMessage id="editPlayLists" defaultMessage="Edit playlist" />
The style doesn't match the Figma prototype.

2024-05-31 02:01 UTC, okeinom commented on src/containers/library/playlist/detail.tsx
> +					<FormattedMessage id="not_shareable_title" defaultMessage="PRIVATE" />
done

2024-05-31 02:04 UTC, okeinom commented on src/pages/[language]/playlists/new/index.tsx
> +//import { useRouter } from 'next/router';
done

2024-05-31 02:11 UTC, okeinom commented on src/styles/styles.scss
> +	margin-bottom: 1px;
updated

2024-05-31 02:17 UTC, okeinom commented on src/components/molecules/teaseRecording.tsx
> +							setIsPlaylistModalOpen(false);
done

2024-05-31 11:20 UTC, okeinom commented on src/components/molecules/teaseRecording.tsx
> +					<div
done

2024-05-31 11:50 UTC, okeinom commented on src/components/molecules/teaseRecording.tsx
> +					<FormattedMessage id="new_playlist" defaultMessage="New playlist" />
updated

2024-05-31 14:06 UTC, okeinom commented on src/pages/[language]/playlists/PlaylistForm.tsx
> +					<FormattedMessage id="editPlayLists" defaultMessage="Edit playlist" />
updated

2024-05-31 17:29 UTC, alangumer commented
Move addToPlaylist, edit, new, and PlaylistForm to library/playlists.

2024-06-04 19:03 UTC, okeinom commented
> Move addToPlaylist, edit, new, and PlaylistForm to library/playlists.

Just Moved addToPlaylist

2024-06-04 19:37 UTC, okeinom commented on src/pages/[language]/library/playlists/PlaylistForm.tsx
> +					type={!id ? 'primary' : 'primaryInverse'}
not sure what you are referring to here.

2024-06-04 19:42 UTC, okeinom commented on src/components/molecules/teaseRecording.module.scss
> +	color: #ff224a;
updated

2024-06-04 19:42 UTC, okeinom commented on src/components/organisms/modal.module.scss
> +	color: #ff224a;
updated

2024-06-04 19:44 UTC, okeinom commented on src/containers/library/playlist/detail.module.scss
> +	color: #ff224a;
updated

2024-06-04 19:57 UTC, okeinom commented on src/components/organisms/modal.tsx
> +						<Heading2 className={styles.centerText}>{title}</Heading2>
updated

2024-06-04 19:58 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +				onCancel={() => onClose()}
updated

2024-06-04 19:59 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +				id={id as string}
updated

2024-06-04 20:02 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +EditPlaylist.displayName = 'EditPlaylist';
getting an error that it's needed.  maybe because i'm exposing an internal function

2024-06-04 20:09 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +const EditPlaylist = forwardRef<EditPlaylistRef, EditPlaylistProps>(
i need this to connect the delete button on the modal to form

2024-06-04 20:12 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +		useImperativeHandle(ref, () => ({
...

2024-06-04 20:25 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +						router.push(`/${language}/library/playlists`);
closed modal and go back. 	
onClose();
router.back();

2024-06-04 20:26 UTC, okeinom commented on src/pages/[language]/library/playlists/new/index.tsx
> +			<PlaylistForm onSubmit={add} onCancel={cancel} />
updated

2024-06-04 20:27 UTC, okeinom commented on src/pages/[language]/library/playlists/PlaylistForm.tsx
> +									id="onlyYow"
updated

2024-06-04 20:36 UTC, okeinom commented on src/components/constants/mutations/useRecordingPlaylist.ts
> +		queryClient.fetchQuery(PLAYLIST_REFETCH_QUERIES);
updated

2024-06-04 20:50 UTC, okeinom commented on src/containers/library/playlist/detail.tsx
> +					{router.route === '/[language]/playlists/[playlist]' ? (
updated

2024-06-04 20:51 UTC, okeinom commented on src/pages/[language]/playlists/addToPlaylist/AddToPlaylistItem.tsx
> +	if (!playlist) {
updated

2024-06-04 20:53 UTC, okeinom commented on src/components/constants/mutations/useRecordingPlaylist.ts
> +				queryClient.invalidateQueries(PLAYLIST_REFETCH_QUERIES);
removing this breaks the code

2024-06-04 21:05 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +					router.reload();
how do i refresh the page to show the updates?

2024-06-04 21:12 UTC, okeinom commented on src/pages/[language]/playlists/addToPlaylist/PlaylistItem.tsx
> +		<div onClick={onPress} className={styles.pressable}>
updated

2024-06-04 22:55 UTC, alangumer commented on src/pages/[language]/library/playlists/edit/index.tsx
> +const EditPlaylist = forwardRef<EditPlaylistRef, EditPlaylistProps>(
It's not necessary, this is a standard component.

2024-06-04 22:57 UTC, alangumer commented on src/pages/[language]/library/playlists/edit/index.tsx
> +					router.reload();
Refetch the query that gets the playlist detail when the update is successful.

2024-06-05 01:00 UTC, okeinom commented on src/graphql/query.graphql
> +mutation playlistAdd($input: UserPlaylistAddInput!) {
updated

2024-06-05 13:12 UTC, okeinom commented on src/pages/[language]/library/playlists/PlaylistForm.tsx
> +					type={!id ? 'primary' : 'primaryInverse'}
No it looks like the app. I created the missing tertiary style type.

2024-06-05 13:56 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +					router.reload();
updated

2024-06-05 14:23 UTC, alangumer commented on src/pages/[language]/library/playlists/edit/index.tsx
> +EditPlaylist.displayName = 'EditPlaylist';
It's not necessary, this is a standard component.

2024-06-05 14:35 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +const EditPlaylist = forwardRef<EditPlaylistRef, EditPlaylistProps>(
updated the code

2024-06-05 14:42 UTC, okeinom commented on src/pages/[language]/library/playlists/addToPlaylist/AddToPlaylistItem.tsx
> +	const isRecordingInPlaylist = playlist?.recordings.edges?.find(
I know but I get a build error and no Vercel preview :(

2024-06-05 14:46 UTC, okeinom commented on src/components/molecules/teaseRecording.tsx
> +				rightElmt={<></>}
updated.

2024-06-05 15:50 UTC, okeinom commented on src/components/constants/mutations/useRecordingPlaylist.ts
> +				queryClient.invalidateQueries(PLAYLIST_REFETCH_QUERIES);
updated

2024-06-05 18:31 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +EditPlaylist.displayName = 'EditPlaylist';
updated

2024-06-05 18:33 UTC, okeinom commented on src/pages/[language]/library/playlists/PlaylistForm.tsx
> +					type={!id ? 'primary' : 'primaryInverse'}
updated

2024-06-06 22:15 UTC, alangumer requested changes

2024-06-06 22:15 UTC, alangumer commented on src/pages/[language]/library/playlists/new/index.tsx
> +			{isLoading && (
Remove the loading, error, and success messages, they are not in the design.

2024-06-06 22:15 UTC, alangumer commented on src/pages/[language]/library/playlists/addToPlaylist/PlaylistList.tsx
> +							defaultMessage="Scroll down for more"
This is not in the design, remove it.

2024-06-06 22:15 UTC, alangumer commented on src/pages/[language]/library/playlists/addToPlaylist/PlaylistItem.tsx
> +						<FormattedMessage id="loading" defaultMessage="Loading..." />
This is not in the design, remove it.

2024-06-06 22:29 UTC, alangumer commented on src/containers/library/playlist/list.tsx
> +	useEffect(() => {
Not resolved.

2024-06-06 22:30 UTC, alangumer commented on src/components/organisms/modal.tsx
> +						<Heading2 className={styles.centerText}>{title}</Heading2>
Not resolved.

2024-06-06 22:31 UTC, alangumer commented on src/pages/[language]/library/playlists/addToPlaylist/AddToPlaylistItem.tsx
> +	const isRecordingInPlaylist = playlist?.recordings.edges?.find(
Then the error is somewhere else, take a look at the parent component.

2024-06-06 23:23 UTC, okeinom commented on src/containers/library/playlist/list.tsx
> +	useEffect(() => {
whats not necessary, the useEffect? I moved the isScrollable. will check.

2024-06-07 00:15 UTC, okeinom commented on src/containers/library/playlist/list.tsx
> +	useEffect(() => {
updated

2024-06-07 00:46 UTC, okeinom commented on src/components/organisms/modal.tsx
> +						<Heading2 className={styles.centerText}>{title}</Heading2>
Updated this to take a titleLeft without a right elmt... this is used in the New Playlist form

2024-06-07 00:52 UTC, okeinom commented on src/pages/[language]/library/playlists/addToPlaylist/AddToPlaylistItem.tsx
> +	const isRecordingInPlaylist = playlist?.recordings.edges?.find(
updated

2024-06-07 00:54 UTC, okeinom commented on src/pages/[language]/library/playlists/PlaylistForm.tsx
> +							e.preventDefault();
updated

2024-06-07 00:54 UTC, okeinom commented on src/pages/[language]/library/playlists/PlaylistForm.tsx
> +							e.preventDefault();
updated

2024-06-07 00:55 UTC, okeinom commented on src/pages/[language]/library/playlists/PlaylistForm.tsx
> +					<button
updated

2024-06-07 00:55 UTC, okeinom commented on src/pages/[language]/library/playlists/PlaylistForm.tsx
> +						className={styles.privacyOption}
updated

2024-06-07 00:56 UTC, okeinom commented on src/components/organisms/modal.tsx
> +	rightElmt?: string | JSX.Element | boolean;
updated

2024-06-07 01:47 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +const useEditPlaylist = (id: number | string, onClose: () => void) => {
updated

2024-06-07 01:48 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +	deletePlaylistRef,
updated

2024-06-07 12:17 UTC, okeinom commented on src/components/molecules/card/PlaylistCard.graphql
> +fragment PlaylistCard on UserPlaylist {
Why, it's being used...?

2024-06-07 12:40 UTC, okeinom commented on src/containers/library/playlist/query.graphql
> +query getLibraryPlaylists($language: Language!) {
updated

2024-06-07 15:37 UTC, okeinom commented on src/components/molecules/teaseRecording.tsx
> +				<div className={clsx(styles.like, unpadded && styles.likeUnpadded)}>
updated

2024-06-07 15:40 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +				router.replace(router.asPath);
refetch not  working out for me. not sure why.

2024-06-07 15:43 UTC, okeinom commented on src/components/molecules/teaseRecording.tsx
> +		<>
updated

2024-06-07 15:46 UTC, okeinom commented on src/components/molecules/teaseRecording.tsx
> +	const iconColor = BaseColors.MID_TONE;
updated

2024-06-07 15:51 UTC, okeinom commented on src/containers/library/playlist/detail.tsx
> +							shareUrl={`https://audioverse.org/${languageRoute}/playlists/${playlist.id}`}
updated

2024-06-07 15:52 UTC, okeinom commented on src/lib/hooks/usePreviousRoute.ts
> +const usePreviousRoute = () => {
done

2024-06-07 15:56 UTC, okeinom commented on src/pages/[language]/library/playlists/addToPlaylist/AddToPlaylist.tsx
> +const PlaylistsPage: React.FC<PlaylistsPageProps> = ({ language, recId }) => {
updated

2024-06-07 15:59 UTC, okeinom commented on src/pages/[language]/library/playlists/addToPlaylist/PlaylistList.module.css
> +/* components/PlaylistList.module.css */
updated

2024-06-07 16:08 UTC, okeinom commented on src/pages/[language]/library/playlists/new/index.tsx
> +			{isLoading && (
updated

2024-06-07 16:18 UTC, okeinom commented on src/pages/[language]/library/playlists/addToPlaylist/PlaylistList.tsx
> +							defaultMessage="Scroll down for more"
updated

2024-06-07 16:23 UTC, okeinom commented on src/pages/[language]/library/playlists/addToPlaylist/PlaylistItem.tsx
> +						<FormattedMessage id="loading" defaultMessage="Loading..." />
updated

2024-06-10 13:30 UTC, okeinom commented on src/components/molecules/card/PlaylistCard.graphql
> +fragment PlaylistCard on UserPlaylist {
Removed. however, i needed to updated the playlist.graphql, so the cardPlaylist is now used with out error.

2024-06-10 14:17 UTC, okeinom commented on src/pages/[language]/library/playlists/Playlistform.module.scss
> +.privacyOption:hover {
updated and added: 
.privacyOption:focus {
	background-color: $ts-darkened-white;
} 
this  will give the press effect like on the app.

2024-06-10 14:51 UTC, okeinom commented on src/components/molecules/buttonAddToPlaylist.tsx
> +		defaultMessage: 'Playlist',
updated

2024-06-10 17:36 UTC, okeinom commented on src/components/molecules/buttonAddToPlaylist.tsx
> +							setIsPlaylistModalOpen(false);
updated

2024-06-10 17:38 UTC, okeinom commented on src/components/molecules/buttonAddToPlaylist.tsx
> +		setIsPlaylistModalOpen(true);
updated

2024-06-10 21:16 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +				router.replace(router.asPath);
I have updated and now refetching. but getting a type error. so hope we can have a quick look at it when you'r back. John also said they would like it ready live for a Demo Alistair has with 3ABN this Wed.

2024-06-11 16:05 UTC, alangumer commented on src/components/molecules/buttonAddToPlaylist.tsx
> +			<IconButton
On the playlist details page.

2024-06-11 16:30 UTC, alangumer commented on src/pages/[language]/library/playlists/edit/index.tsx
> +				router.replace(router.asPath);
Use the invalidateQueries function from react-query.

2024-06-11 18:39 UTC, alangumer requested changes

2024-06-11 18:39 UTC, alangumer commented on src/components/molecules/buttonAddToPlaylist.tsx
> +		setRefreshKey((prevKey) => prevKey + 1); // Trigger refresh
Remove this, and when the new playlist was added successfully, invalidate the query that gets the playlists data in order to trigger a refetch.

2024-06-11 20:27 UTC, okeinom commented on src/components/molecules/buttonAddToPlaylist.tsx
> +		setRefreshKey((prevKey) => prevKey + 1); // Trigger refresh
updated and now invalidating this: queryClient.invalidateQueries(PLAYLIST_REFETCH_QUERIES);

2024-06-11 20:44 UTC, okeinom commented on src/pages/[language]/library/playlists/PlaylistForm.tsx
> +							<p className={styles.privacyOptionSubtitle}>
updated

2024-06-11 20:50 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +				router.replace(router.asPath);
ok, so do i keep the current implementation?

2024-06-11 21:04 UTC, okeinom commented on src/components/molecules/buttonAddToPlaylist.tsx
> +			<IconButton
ok, need to look into this, it's getting a odd class attached. thanks for the heads up

2024-06-11 23:47 UTC, okeinom commented on src/components/molecules/buttonAddToPlaylist.tsx
> +			<IconButton
So what I saw was that on the playlist details page was that i was getting this background color: $ts-darkened-playlistB: #ffffff; and not this one: $ts-darkened-white: #f8f8f8; .... So I updated here: playlistItem: BaseColors.WHITE. All seem to work now.

2024-06-12 13:25 UTC, alangumer commented on src/pages/[language]/library/playlists/edit/index.tsx
> +				router.replace(router.asPath);
Yes.

2024-06-12 13:43 UTC, alangumer commented on src/components/molecules/buttonAddToPlaylist.tsx
> +			<IconButton
Change the color in BaseColors.PLAYLIST_B.

2024-06-12 15:33 UTC, alangumer commented on src/pages/[language]/library/playlists/addToPlaylist/AddToPlaylistItem.tsx
> +	const isRecordingInPlaylist = playlist?.recordings.edges?.find(
According to this https://nextjs.org/docs/messages/prerender-error it looks like this issue is because there are components inside the pages folder. You can just move PlaylistForm.tsx, PlaylistForm.module.scss, and the components inside the addToPlaylist folder to where correspond in the components folder.

2024-06-12 15:39 UTC, okeinom commented on src/components/molecules/buttonAddToPlaylist.tsx
> +			<IconButton
I updated to color but still not hovering

2024-06-12 15:39 UTC, okeinom commented on src/pages/[language]/library/playlists/edit/index.tsx
> +				router.replace(router.asPath);
so leave this as i know have it... ok

2024-06-12 15:51 UTC, alangumer requested changes

2024-06-12 15:51 UTC, alangumer commented on src/pages/[language]/library/playlists/addToPlaylist/AddToPlaylistItem.tsx
> +	const isRecordingInPlaylist = playlist?.recordings?.edges?.find(
Recordings is a required property.

2024-06-12 17:04 UTC, okeinom commented on src/components/molecules/buttonAddToPlaylist.tsx
> +			<IconButton
fixed

2024-06-12 17:31 UTC, okeinom commented on src/pages/[language]/library/playlists/addToPlaylist/AddToPlaylistItem.tsx
> +	const isRecordingInPlaylist = playlist?.recordings?.edges?.find(
updated

2024-06-12 17:41 UTC, alangumer approved these changes

2024-06-12 19:09 UTC, merged