updated play button for tease
audioverse-org/audioverse-next pull request #535
Opened 2024-06-11 19:41 UTC by okeinom

2024-06-24 21:29 UTC, okeinom commented
https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-1076

2024-06-25 17:34 UTC, alangumer requested changes
Fix the translations for time left.

2024-06-25 17:34 UTC, alangumer commented on src/components/molecules/teaseRecording.module.scss
> +	padding-bottom: 4px;
On small screens, when the title is longer than two lines, the top of the third line is shown, one way to fix it is to reduce the padding to 2px.

2024-06-25 18:13 UTC, okeinom commented on src/components/atoms/playButtonCurrentLockup.tsx
> +const PlayButtonCurrentLockup: React.FC<PlayButtonCurrentProps> = ({
removed

2024-06-25 18:13 UTC, okeinom commented on src/components/molecules/buttonPlayCircle.tsx
> +							isCurrentTrack={true}
updated

2024-06-25 18:18 UTC, okeinom commented on src/components/molecules/buttonPlayCircle.tsx
> +				{isCurrentTrack ? (
not sure what you'r talking about here...

2024-06-25 18:20 UTC, okeinom commented on src/components/atoms/playProgress.tsx
> +	activeColor?: string;
updated

2024-06-25 18:45 UTC, okeinom commented on src/components/atoms/playTime.tsx
> +					[styles[textSecondaryColor]]: textSecondaryColor,
updated

2024-06-25 18:46 UTC, okeinom commented on src/components/atoms/playTime.tsx
> +const PlayTime: React.FC<Props> = ({
removed

2024-06-25 18:49 UTC, okeinom commented on src/components/molecules/teaseRecording.module.scss
> +	padding-bottom: 4px;
updated

2024-06-26 14:10 UTC, alangumer commented on src/components/molecules/buttonPlayCircle.tsx
> +				{isCurrentTrack ? (
Remove the isCurrentTrack validation, and add it along with the session.progress validation in line 70, and update the properties for PlayProgress as needed.

2024-06-26 15:25 UTC, okeinom commented on src/components/molecules/buttonPlayCircle.tsx
> +				{isCurrentTrack ? (
updated. Thanks.

2024-06-26 15:58 UTC, alangumer approved these changes

2024-06-26 15:58 UTC, alangumer commented on src/components/molecules/buttonPlayCircle.tsx
> +			<>
Remove this.

2024-06-26 17:20 UTC, merged