Account page tabs perf
audioverse-org/audioverse-next pull request #544
Opened 2024-06-20 16:37 UTC by narthur

2024-07-11 21:16 UTC, alangumer requested changes

2024-07-11 21:16 UTC, alangumer commented on src/containers/presenter/list/all.tsx
> +	const { data, hasNextPage, fetchNextPage, isFetching } = useInfiniteQuery(
The prefetch is not working, the first page is being fetched twice, take a look at https://audioverse7.atlassian.net/browse/AV-1153.

2024-07-17 14:08 UTC, narthur commented on next.config.js
> +				},
Removed!

2024-07-17 17:09 UTC, alangumer approved these changes

2024-07-17 17:59 UTC, merged