Prevent video from pausing when user navigates away from associated detail page
audioverse-org/audioverse-next pull request #546
Opened 2024-06-24 16:25 UTC by narthur

Apologies for the super ugly hack. We spent a lot of time over here trying to find the cause of the bug so we could fix it properly, but we failed in the end.

2024-07-11 21:27 UTC, alangumer requested changes

2024-07-11 21:27 UTC, alangumer commented on src/components/templates/andPlaybackContext.tsx
> +		if (_paused) {
Use playback.paused() direclty.

2024-07-17 14:12 UTC, narthur commented on src/components/templates/andPlaybackContext.tsx
> +		if (_paused) {
@alangumer I think this would defeat the purpose, since the goal is to restore the player to the state it was before the move. If I checked what state it was after the move, I wouldn't be restoring to what it was before the move.

2024-07-17 17:12 UTC, alangumer commented on src/components/templates/andPlaybackContext.tsx
> +		if (_paused) {
@narthur I see, ok.

2024-07-17 17:12 UTC, alangumer approved these changes

2024-07-17 18:24 UTC, merged