added open app button for mobile
audioverse-org/audioverse-next pull request #548
Opened 2024-06-25 16:52 UTC by okeinom

2024-06-25 19:44 UTC, okeinom commented
https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-804

2024-06-25 21:29 UTC, alangumer requested changes

2024-06-25 21:29 UTC, alangumer commented on src/components/molecules/openAppButton.tsx
> +	useEffect(() => {
Remove this and move isIOS and isAndroid out, and do the validations based on those values.

2024-06-26 13:18 UTC, okeinom commented on src/components/molecules/openAppButton.tsx
> +	useEffect(() => {
I did a small update, however, we need the useEffect to ensure the userAgent runs in the client side and that navigator can be found.

2024-06-26 14:12 UTC, alangumer approved these changes

2024-06-26 14:12 UTC, alangumer commented on src/components/molecules/openAppButton.tsx
> +	useEffect(() => {
I see, ok.

2024-06-26 14:21 UTC, merged