Add Share Link
audioverse-org/audioverse-next pull request #549
Opened 2024-06-25 18:53 UTC by jperegrino75

Added "Sharing Tools" Link to more menu

2024-06-25 20:51 UTC, alangumer requested changes
The translations are missing.

2024-06-25 20:51 UTC, alangumer commented on src/lib/useNavigationItems.tsx
> +					href: 'http://share.audioverse.org/',
Should be https and there is no need for the slash at the end.

2024-06-26 16:03 UTC, jperegrino75 commented on src/lib/useNavigationItems.tsx
> +					href: 'http://share.audioverse.org/',
done and committed

2024-06-26 16:13 UTC, alangumer approved these changes

2024-06-26 17:47 UTC, jperegrino75 commented
> The translations are missing.

we will keep the link to English in all languages as this is the way the other pages are currently.

2024-06-27 13:43 UTC, jperegrino75 commented
@alangumer I resolved the conflicts by removing the code. This was for internationalization of the Sharing Link but since this is the same for all languages; I just removed the code. Hope I did it in the right way :-)

2024-07-02 21:19 UTC, merged