Av 1181 condensed cards to use new layout on recent and trending cards website
audioverse-org/audioverse-next pull request #553
Opened 2024-07-10 19:02 UTC by okeinom

2024-07-16 15:15 UTC, okeinom commented
https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-1181

2024-07-17 16:44 UTC, alangumer requested changes

2024-07-17 16:44 UTC, alangumer commented on src/components/molecules/card/hat/audiobook.tsx
> -			<CardRecordingSequenceHat sequence={sequence} inverse>
Remove all the properties but collection { title } from recordingSequenceHat.graphql, and remove recordings from sequenceIsFavorited.graphql and recordingsFavoritedCount from useIsSequenceFavorited.ts.

2024-07-17 16:44 UTC, alangumer commented on src/components/molecules/card/hat/index.tsx
>  type SimpleProps = {
Rename to Props.

2024-07-17 16:44 UTC, alangumer commented on src/components/molecules/card/hat/sponsor.tsx
> +	className?: string;
Remove the className, and move the styles to this component since it's based on the fullBleed property.

2024-07-22 18:52 UTC, okeinom commented on src/components/molecules/card/hat/audiobook.tsx
> -			<CardRecordingSequenceHat sequence={sequence} inverse>
updated

2024-07-22 18:52 UTC, okeinom commented on src/components/molecules/card/hat/sponsor.tsx
> +	className?: string;
updated

2024-07-23 21:23 UTC, alangumer approved these changes

2024-07-24 12:35 UTC, merged