Continue Listening Section
audioverse-org/audioverse-next pull request #564
Opened 2024-08-07 21:13 UTC by narthur

This PR is for the purpose of completing [AV-78](https://audioverse7.atlassian.net/browse/AV-78?atlOrigin=eyJpIjoiNDAyZDhiNTA2NTBmNDljZmEzNTc4YzFjZjQwN2E5YjIiLCJwIjoiaiJ9).

2024-08-12 20:15 UTC, narthur reviewed
Looking good!

2024-08-12 20:15 UTC, narthur commented on src/containers/discover/index.tsx
> +	const user = authResult.data?.me?.user;
Let's extract this into a new hook in lib/hooks, something like useMe.ts, and give it its own graphql query, useMe.graphql. And let's use the same hook inside withAuthGuard.

2024-08-13 13:56 UTC, narthur reviewed
lgtm! 🚀

2024-08-30 13:07 UTC, narthur reviewed
Great work!

2024-08-30 13:07 UTC, narthur commented on src/components/organisms/cardSlider/section/index.tsx
> +				<CardSlider {...props} items={loadingCards} />
Now that we're server-rendering the discover page, can we rip out the loading state we added? If I'm thinking right, it would never be visible.

2024-08-30 13:20 UTC, narthur commented on src/components/organisms/cardSlider/section/index.module.scss
> +.hidden {
Do we still need this class?

2024-08-30 13:43 UTC, narthur reviewed
lgtm! 🚀

2024-09-04 18:05 UTC, alangumer requested changes

2024-09-04 18:05 UTC, alangumer commented on src/components/organisms/cardSlider/section/index.tsx
> +	const loadingCards: JSX.Element[] = [];
Not used.

2024-09-04 18:05 UTC, alangumer commented on src/pages/[language]/discover/index.ts
> +export async function getServerSideProps({
Why was this changed to server side?

2024-09-04 19:56 UTC, jakecoble commented on src/pages/[language]/discover/index.ts
> +export async function getServerSideProps({
Featured Teachings was appearing and disappearing during page load if the user was logged in. It didn't look great, and some of the other solutions we came up with were awkward, so we moved the rendering server side.

2024-09-10 20:59 UTC, alangumer commented on src/pages/[language]/discover/index.ts
> +export async function getServerSideProps({
I see, this is one of the main pages, so it gets a lot of loads, so I'd suggest to keep it static to take advantage of Vercel page caching.

2024-09-13 15:30 UTC, alangumer commented on src/components/organisms/cardSlider/section/index.tsx
> +	const renderFail = cards.length < 1;
This is only used once, move it to the if.

2024-09-13 15:31 UTC, alangumer commented on src/containers/discover/index.tsx
> +		if (options.count ?? 0 > 0) return 'continueListening';
There is no need to use ?? since undefined is not greater than 0.

2024-09-13 15:34 UTC, alangumer approved these changes

2024-09-13 15:45 UTC, jakecoble commented on src/containers/discover/index.tsx
> +		if (options.count ?? 0 > 0) return 'continueListening';
The TypeScript compiler complains if we don't ensure that `options.count` is a number.

`[checkTs] src/containers/discover/index.tsx(34,7): error TS18048: 'options.count' is possibly 'undefined'.`

2024-09-19 12:23 UTC, merged