Fix prefetching and hydration
audioverse-org/audioverse-next pull request #570
Opened 2024-08-16 13:08 UTC by jakecoble

2024-08-21 13:29 UTC, narthur requested changes
Great work!

2024-08-21 13:29 UTC, narthur commented on src/lib/hooks/useIsAuthenticated.ts
> +import { useGetWithAuthGuardDataQuery } from '~components/HOCs/__generated__/withAuthGuard';
Since this graphql query is associated with the hook instead of the HOC now, let's move it to useIsAuthenticated.graphql and call the query something like `getIsAuthenticated`.

2024-08-21 13:34 UTC, jakecoble commented
Steps used to identify missing prefetches:

1. Open site in a new window
2. Block https://graphql.audioverse.org/graphql
3. Scroll through each page, comparing two versions of the site: one with the graphql endpoint blocked and one with the endpoint unblocked.
4. Ensure those sections are fetched in prefetchQueries in that page's getServerSideProps and getStaticProps functions.

Steps used to find fetches that weren't using the generated queries:

1. Grep codebase for @tanstack/react-query imports.
2. Modify files using react-query directly to use the generated query code.

2024-08-27 17:49 UTC, jakecoble commented on src/lib/hooks/useIsAuthenticated.ts
> +import { useGetWithAuthGuardDataQuery } from '~components/HOCs/__generated__/withAuthGuard';
Should be done in the latest commit.

2024-08-30 13:30 UTC, narthur commented
Great work, @jakecoble!

2024-09-19 19:10 UTC, narthur approved these changes
Great work!

2024-09-27 15:48 UTC, alangumer approved these changes
Great work!

2024-09-27 16:12 UTC, merged