Update Dependencies
audioverse-org/audioverse-next pull request #576
Opened 2024-08-30 13:34 UTC by jakecoble

2024-08-30 18:04 UTC, narthur requested changes
Good work!

2024-08-30 18:47 UTC, jakecoble commented on src/components/molecules/searchBar.tsx
> +						return lastTerm != term && term != ''
Failed to notice that this lambda doesn't return the result of its last expression.

2024-09-02 15:01 UTC, jakecoble commented on src/lib/useNavigationItems.tsx
> +		...opts,
Found the reason for the spreading.

https://github.com/audioverse-org/audioverse-next/actions/runs/10668784892/job/29569272384?pr=576#step:7:23
https://nextjs.org/docs/messages/invalid-dynamic-options-type

2024-09-03 13:04 UTC, narthur commented
@jakecoble Looks like the accessibility scan found a bunch of new instances of this error:

WCAG2AA.Principle2.Guideline2_4.2_4_1.H64.1

https://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/

2024-09-30 15:04 UTC, narthur approved these changes
> Reviewed 336 of 336 files at r1.
> *[Reviewable](https://reviewable.io/reviews/audioverse-org/audioverse-next/576)* status: 333 of 336 files reviewed, 13 unresolved discussions (waiting on @alangumer and @jakecoble)

___
*[`.husky/pre-commit` line 3 at r1](https://reviewable.io/reviews/audioverse-org/audioverse-next/576#-O7y67N3Baj2Aooob18G:-O7y67N3Baj2Aooob18H:b-aso6t9) ([raw file](https://github.com/audioverse-org/audioverse-next/blob/b16dbb14c377169cdbfd71bebb4f6c3e56160f23/.husky/pre-commit#L3)):*
> ```
> #!/usr/bin/env sh
> . "$(dirname -- "$0")/_/husky.sh"
> ```

Did you confirm that the hook still works after this change?
___
*[`src/components/molecules/navItem.tsx` line 43 at r1](https://reviewable.io/reviews/audioverse-org/audioverse-next/576#-O7y9iOJEmtxy6x15pPc:-O7y9iOJEmtxy6x15pPd:bbpcl30) ([raw file](https://github.com/audioverse-org/audioverse-next/blob/e954d23fff44d3b6852f370686886da537818f80/src/components/molecules/navItem.tsx#L43)):*
> ```XML
> 					onClick={() => {
> 						analytics.track('Menu click', { label });
> 						return setSubmenu(key);
> ```

I don't think this needs to be returned.
___
*[`src/components/organisms/cardSlider/index.spec.tsx` line 17 at r1](https://reviewable.io/reviews/audioverse-org/audioverse-next/576#-O7yDbkM79fBRXSGBwDW:-O7yDbkM79fBRXSGBwDX:bdk7ku9) ([raw file](https://github.com/audioverse-org/audioverse-next/blob/e954d23fff44d3b6852f370686886da537818f80/src/components/organisms/cardSlider/index.spec.tsx#L17)):*
> ```XML
> 	previous: 'previous',
> 	next: 'next',
> 	items: [undefined],
> ```

Why is this needed?
___
*[`src/components/organisms/cardSlider/section/continueListening.tsx` line 33 at r1](https://reviewable.io/reviews/audioverse-org/audioverse-next/576#-O7yDpKi0k2fv7-dqrhR:-O7yDpKi0k2fv7-dqrhS:b-graw8d) ([raw file](https://github.com/audioverse-org/audioverse-next/blob/e954d23fff44d3b6852f370686886da537818f80/src/components/organisms/cardSlider/section/continueListening.tsx#L33)):*
> ```XML
> 			selectNodes={(p) =>
> 				(
> 					p as GetSectionContinueListeningQuery
> ```

Ideally this would be inferred automatically from the other passed attributes. But I understand that can be tricky.
___
*[`src/components/templates/andPlaybackContext.tsx` line 464 at r1](https://reviewable.io/reviews/audioverse-org/audioverse-next/576#-O7yEVB-7-3h8tr4N0Xu:-O7yEVB-7-3h8tr4N0Xv:b-1anzel) ([raw file](https://github.com/audioverse-org/audioverse-next/blob/b16dbb14c377169cdbfd71bebb4f6c3e56160f23/src/components/templates/andPlaybackContext.tsx#L464)):*
> ```XML
> 			};
> 
> 			const options: VideoJs.VideoJsPlayerOptions = {
> ```

It would be nice if we could figure out a way to keep this
___
*[`src/containers/base.spec.tsx` line 50 at r1](https://reviewable.io/reviews/audioverse-org/audioverse-next/576#-O7yEod_CNIx5TzOSoa2:-O7yEod_CNIx5TzOSoa3:b-o6nzmq) ([raw file](https://github.com/audioverse-org/audioverse-next/blob/e954d23fff44d3b6852f370686886da537818f80/src/containers/base.spec.tsx#L50)):*
> ```XML
> 				const { data: myQuery } = useQuery({
> 					queryKey: ['myQuery'],
> 					...jest.fn(),
> ```

This looks weird to me. Is spreading `jest.fn()` the right way to do this?
___
*[`src/lib/usePlaybackSession.tsx` line 87 at r1](https://reviewable.io/reviews/audioverse-org/audioverse-next/576#-O7yGOKVEVrBxPexImgi:-O7yGOKVEVrBxPexImgj:b-va7r8r) ([raw file](https://github.com/audioverse-org/audioverse-next/blob/e954d23fff44d3b6852f370686886da537818f80/src/lib/usePlaybackSession.tsx#L87)):*
> ```XML
> 		},
> 		{
> 			queryKey: ['playback-progress', recording?.id || 0],
> ```

Why are you manually setting the query key here? Shouldn't that be handled by the generated code?


<!-- Sent from Reviewable.io -->

2024-10-16 18:59 UTC, alangumer requested changes
Great work! Just a couple of comments.

2024-10-16 18:59 UTC, alangumer commented on src/components/organisms/cardSlider/section/continueListening.tsx
> +					p as GetSectionContinueListeningQuery
The type assertion is not necessary, remove it.

2024-10-16 18:59 UTC, alangumer commented on src/components/organisms/cardSlider/section/continueListening.tsx
>  			Card={(p: { node: CardRecordingFragment }) => (
Same here.

2024-10-16 18:59 UTC, alangumer commented on src/components/organisms/cardSlider/section/trendingMusic.tsx
> +				(p as GetSectionTrendingMusicQuery)?.trendingMusic.nodes?.map(
The type assertion is not necessary, remove it.

2024-10-16 18:59 UTC, alangumer commented on src/components/organisms/cardSlider/section/trendingMusic.tsx
>  			Card={(p: { node: CardRecordingFragment }) => (
Same here.

2024-10-16 18:59 UTC, alangumer commented on src/components/organisms/cardSlider/section/trendingTeachings.tsx
> +				(p as GetSectionTrendingTeachingsQuery)?.trendingTeachings.nodes?.map(
The type assertion is not necessary, remove it.

2024-10-16 18:59 UTC, alangumer commented on src/components/organisms/cardSlider/section/trendingTeachings.tsx
>  			Card={(p: { node: CardRecordingFragment }) => (
Same here.

2024-10-16 18:59 UTC, alangumer commented on src/components/organisms/cardSlider/section/index.tsx
> +			{ language, after: 'after' },
Why after: 'after'?

2024-10-16 18:59 UTC, alangumer commented on src/containers/presenter/list/all.tsx
> +				after: 'after',
Same here.

2024-10-16 18:59 UTC, alangumer commented on src/containers/sponsor/list/all.tsx
> +			{ language, after: 'after' },
Same here.

2024-10-23 16:24 UTC, alangumer commented on src/components/organisms/cardSlider/section/trendingMusic.tsx
>  			Card={(p: { node: CardRecordingFragment }) => (
Never mind.

2024-10-23 16:31 UTC, alangumer requested changes

2024-10-23 16:31 UTC, alangumer commented on src/components/organisms/cardSlider/section/index.tsx
It looks that for the type inference to work for selectPageInfo when the component is used, the type should be PageInfoSelector<InferGraphqlInfiniteQueryType<T>>.

2024-10-24 14:10 UTC, alangumer approved these changes

2024-10-24 14:12 UTC, narthur commented on src/components/organisms/cardSlider/section/index.tsx
Resolved

2024-10-24 14:31 UTC, merged