Av 1340 conference page add horizontal scrolling website
audioverse-org/audioverse-next pull request #580
Opened 2024-09-30 13:34 UTC by okeinom

2024-10-02 20:24 UTC, okeinom commented
https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-1340

2024-10-09 17:53 UTC, alangumer requested changes
The files audit-ci.json, pa11y-ci.json, and pa11y.json are not related to your changes, revert them.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/section/conferencePresenters.tsx
> +		// eslint-disable-next-line react-hooks/rules-of-hooks
Remove this and fix the warning.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/section/conferenceSeries.tsx
> +		// eslint-disable-next-line react-hooks/rules-of-hooks
Same here.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/section/conferenceTeachings.tsx
> +		// eslint-disable-next-line react-hooks/rules-of-hooks
Same here.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/section/index.module.scss
> +.salmon {
Not used.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/section/index.tsx
> +	const color = isDarkBg ? BaseColors.SALMON : BaseColors.RED;
Only used once, move it to where it's used.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/section/index.tsx
> +						className={isDarkBg ? styles.seeAlldbg : styles.seeAll}
The only difference between seeAlldbg and seeAll is the color, so always add seeAll and conditionally add another other class that adds just the color.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/index.module.scss
> -		--slider-full-width: calc(
Why did you remove this?

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/index.module.scss
> +.whiteBg swiper-slide {
Not ncessary, remove it.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/index.tsx
> +				className={isDarkBg ? styles.arrowSalmon : styles.arrow}
Not necessary, revert it.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/index.tsx
> +				{isDarkBg ? <IconBackWhite /> : <IconBack />}
Use <IconBack color={isDarkBg && '#fff'} /> instead, and remove the new SVG.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/index.tsx
> +			<LazySwiper on={handlers} className={hasBg ? styles.whiteBg : ''}>
Use isDarkBg and remove the property hasBg.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/index.tsx
> +				className={isDarkBg ? styles.arrowSalmon : styles.arrow}
Same here.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/cardSlider/index.tsx
> +				{isDarkBg ? <IconForwardWhite /> : <IconForward />}
Same here.

2024-10-09 17:53 UTC, alangumer commented on src/components/organisms/searchResults.graphql
> +	$collectionId: ID = null
Why did you add this?

2024-10-09 17:53 UTC, alangumer commented on src/containers/collection/detail.module.scss
>  .cardGroup {
Not used.

2024-10-09 17:53 UTC, alangumer commented on src/containers/collection/detail.tsx
> +	const formattedDuration = useFormattedDuration(duration);
Only used once, move it back to where it's used.

2024-10-09 17:53 UTC, alangumer commented on src/containers/collection/presenter.tsx
> +		const fetchCollectionData = async () => {
Remove this and fetch the data on the server side.

2024-10-09 17:53 UTC, alangumer commented on src/pages/[language]/conferences/[id]/presenters/[presenterId].tsx
> +	const result = await getPresenterDetailPageData({
This is not the right query because it fetches data that is not used in this page, create a new one and add the collection data.

2024-10-09 17:53 UTC, alangumer commented on src/containers/collection/presenters.tsx
> +	const altPath = `/${lang}/conferences/${collection.id}/presenters/`;
Remove this and take a look at how the canonicalPath is replaced in containers/library/playlist/detail.tsx.

2024-10-09 17:53 UTC, alangumer commented on src/containers/collection/sequences.tsx
> +	const altPath = `/${lang}/conferences/${collection.id}/presenters/`;
I don't think this is necessary at this level, the link should be to the general presenter's page, so revert the changes.

2024-10-09 17:53 UTC, alangumer commented on src/containers/collection/teachings.tsx
> +	const altPath = `/${lang}/conferences/${collection.id}/presenters/`;
I don't think this is necessary at this level, the link should be to the general presenter's page, so revert the changes.

2024-10-09 17:53 UTC, alangumer commented on src/containers/discover/collections.graphql
> +query getDiscoverCollectionsPageData($collectionId: ID = null) {
Why did you add this?

2024-10-09 17:53 UTC, alangumer commented on src/containers/library/library.graphql
> +	$collectionId: ID = null
Why did you add this?

2024-10-09 17:53 UTC, alangumer commented on src/containers/presenter/detail.graphql
> +query getPresenterDetailPageData(
Revert all the changes in this file.

2024-10-09 17:53 UTC, alangumer commented on src/containers/search/persons.graphql
> +	$collectionId: ID = null
Why did you add this?

2024-10-09 17:53 UTC, alangumer commented on src/containers/collection/presenters.graphql
> +	$collectionId: ID!
Not necessary, revert this.

2024-10-09 17:53 UTC, alangumer commented on src/pages/[language]/conferences/[id]/presenters/page/[i].tsx
> +	const collectionId = params?.id as string;
Not necessary, revert this.

2024-10-09 17:53 UTC, alangumer commented on src/pages/[language]/conferences/[id]/[[...slug]].tsx
> +	const collectionId = params?.id as string;
Revert all the changes here.

2024-10-09 17:53 UTC, alangumer commented on src/containers/collection/detail.graphql
> +query getCollectionDetailPageData(
Revert all the changes in this file, and remove persons, the "first" parameter from sequences and recordings, and nodes and pageInfo from sequences and recordings.

2024-10-09 19:39 UTC, okeinom commented on src/containers/collection/detail.graphql
> +query getCollectionDetailPageData(
updated

2024-10-09 20:00 UTC, okeinom commented on src/containers/collection/presenters.graphql
> +	$collectionId: ID!
updated

2024-10-09 20:01 UTC, okeinom commented on src/containers/search/persons.graphql
> +	$collectionId: ID = null
removed

2024-10-09 20:04 UTC, okeinom commented on src/containers/presenter/detail.graphql
> +query getPresenterDetailPageData(
updated

2024-10-09 20:04 UTC, okeinom commented on src/containers/library/library.graphql
> +	$collectionId: ID = null
removed

2024-10-09 20:06 UTC, okeinom commented on src/containers/discover/collections.graphql
> +query getDiscoverCollectionsPageData($collectionId: ID = null) {
was having an issue. removed.

2024-10-09 20:27 UTC, okeinom commented on src/components/organisms/searchResults.graphql
> +	$collectionId: ID = null
removed

2024-10-09 20:38 UTC, okeinom commented on src/components/organisms/cardSlider/section/index.module.scss
> +.salmon {
removed

2024-10-09 21:08 UTC, okeinom commented on src/components/organisms/cardSlider/section/index.tsx
> +						className={isDarkBg ? styles.seeAlldbg : styles.seeAll}
updated

2024-10-09 21:09 UTC, okeinom commented on src/components/organisms/cardSlider/index.module.scss
> -		--slider-full-width: calc(
I hides the arrows on the conference page when on bigger screens

2024-10-09 21:23 UTC, okeinom commented on src/components/organisms/cardSlider/index.tsx
> +				{isDarkBg ? <IconBackWhite /> : <IconBack />}
updated

2024-10-09 21:38 UTC, okeinom commented on src/components/organisms/cardSlider/index.tsx
> +				className={isDarkBg ? styles.arrowSalmon : styles.arrow}
updated

2024-10-09 21:39 UTC, okeinom commented on src/components/organisms/cardSlider/index.tsx
> +				className={isDarkBg ? styles.arrowSalmon : styles.arrow}
updated

2024-10-09 21:39 UTC, okeinom commented on src/components/organisms/cardSlider/index.tsx
> +				{isDarkBg ? <IconForwardWhite /> : <IconForward />}
updated

2024-10-09 21:41 UTC, okeinom commented on src/containers/collection/detail.module.scss
>  .cardGroup {
removed

2024-10-09 21:43 UTC, okeinom commented on src/components/organisms/cardSlider/index.tsx
> +			<LazySwiper on={handlers} className={hasBg ? styles.whiteBg : ''}>
removed

2024-10-10 11:15 UTC, okeinom commented on src/containers/collection/presenters.tsx
> +	const altPath = `/${lang}/conferences/${collection.id}/presenters/`;
updated

2024-10-10 12:39 UTC, okeinom commented on src/pages/[language]/conferences/[id]/presenters/[presenterId].tsx
> +	const result = await getPresenterDetailPageData({
updated

2024-10-14 10:46 UTC, okeinom commented on src/containers/collection/teachings.tsx
> +	const altPath = `/${lang}/conferences/${collection.id}/presenters/`;
updated

2024-10-14 10:46 UTC, okeinom commented on src/containers/collection/sequences.tsx
> +	const altPath = `/${lang}/conferences/${collection.id}/presenters/`;
updated

2024-10-14 13:30 UTC, okeinom commented on src/containers/collection/presenter.tsx
> +		const fetchCollectionData = async () => {
updated

2024-10-14 14:13 UTC, okeinom commented on src/containers/collection/detail.tsx
> +	const formattedDuration = useFormattedDuration(duration);
updated

2024-10-14 15:56 UTC, okeinom commented on src/components/organisms/cardSlider/index.module.scss
> +.whiteBg swiper-slide {
updated

2024-10-14 16:41 UTC, okeinom commented on src/components/organisms/cardSlider/section/index.tsx
> +	const color = isDarkBg ? BaseColors.SALMON : BaseColors.RED;
updated

2024-10-15 10:56 UTC, okeinom commented on src/components/organisms/cardSlider/section/conferenceTeachings.tsx
> +		// eslint-disable-next-line react-hooks/rules-of-hooks
updated

2024-10-15 10:56 UTC, okeinom commented on src/components/organisms/cardSlider/section/conferenceSeries.tsx
> +		// eslint-disable-next-line react-hooks/rules-of-hooks
updated

2024-10-15 10:57 UTC, okeinom commented on src/components/organisms/cardSlider/section/conferencePresenters.tsx
> +		// eslint-disable-next-line react-hooks/rules-of-hooks
updated

2024-10-17 16:22 UTC, alangumer commented on src/components/organisms/cardSlider/index.module.scss
> -		--slider-full-width: calc(
I see, good catch!

2024-10-17 18:56 UTC, alangumer approved these changes

2024-10-21 15:52 UTC, merged