Bible UI
audioverse-org/audioverse-next pull request #610
Opened 2024-12-26 13:49 UTC by narthur

2024-12-26 16:03 UTC, lcflight approved these changes
Looking good.

2025-03-06 18:22 UTC, alangumer requested changes

2025-03-06 18:22 UTC, alangumer commented on scripts/save-graphql-version-indices.main.ts
> +import fs from 'fs';
This won't work for the Bible "King James Version (AudioVerse)" because new content is being added and a new deployment will be necessary to get the new data. Get the data dynamically as needed, for instance for the versions dropdown just the id and title are necessary, and for the books UI, just the sequences for that Bible.

2025-03-06 18:26 UTC, alangumer requested changes
This is the first pass. Also, there was an error when loading directly en/bibles/ENGKJV2/MAT/3, it looks that the issue is that before it was using the book id and now the book name.

2025-03-07 16:50 UTC, narthur commented on src/services/bibles/getBible.ts
> +				book.chapters_full = await fetchFcbhChapters(
Hmm, I'm going to push back on this one.

`fetchFcbhChapters` uses `fetchResponse`, which in turn uses `manageAsyncFunction`. This means all calls to the FCBH API are memoized, so the referenced code shouldn't result in many duplicate calls to FCBH. We need the data from the fileset in order to determine id, title, and duration of each chapter in `transformVersion`. We have a separate hook, `useAudioUrlRefresh`, which handles refreshing stale FCBH audio URLs on the client.

The current design's goal is to restrict as much of our code as possible from needing to know about FCBH. I'm hopeful in the future we'll find a way for the GraphQL API to be able to proxy FCBH so the public site doesn't need to know anything about the two different audiobible sources. The hope is that handling Bibles the way I have will make that switch as easy as possible whenever that time comes.

2025-03-07 18:38 UTC, alangumer commented on src/services/bibles/getBible.ts
> +				book.chapters_full = await fetchFcbhChapters(
I see. The getBible function is used in bibles/[version].tsx and bibles/[version]/[book]/[chapter], the first route doesn't need the full details and URLs for all the books, just the books that are available, names and ids, so there is no need to call the API, the second route same as the first one, plus detailed information about the book and chapter URL, which is part of the fileset, so it should do just one API call to get the fileset for that book.

2025-03-07 18:43 UTC, alangumer requested changes
Keep the book_id in the URL as it is in production; this allows us to standardize and use the same book_id across languages, also, the app relies on the book_id in the URL for deep linking.

2025-03-09 18:28 UTC, jlaverde77 reviewed
I feel like the CI changes should be separate as this is quite a large change and we have the AV-1514 for it. I'm making the updates in a separate branch and PR and an additionalupdate to e2e.yml file.

2025-03-10 22:42 UTC, alangumer requested changes

2025-03-10 22:42 UTC, alangumer commented on src/services/bibles/fcbh/fetchFcbhBibles.ts
> +export async function fetchFcbhBibles(): Promise<IBibleVersion[] | null> {
Not used, remove it.

2025-03-10 22:42 UTC, alangumer commented on src/containers/bible/chapter.tsx
> +import React, { useEffect, useRef, useState } from 'react';
The GTM push event recording_view is misssing, take a look at recording.tsx.

2025-03-10 22:42 UTC, alangumer commented on src/services/bibles/fcbh/fetchFcbhChapters.ts
> +			id: `${book_id}/${chapter_start}`,
The fileset id is missing in the id: `${bible.fileSetId}/${chapter.book_id}/${chapter.chapter_start}`.

2025-03-10 22:42 UTC, alangumer commented on src/services/bibles/transforms/chapterTransforms.ts
> +		sequence: null,
Specify at least the sequence title, which is the book name, this is used for playback tracking purposes on GTM, take a look at transformBibleBrainChapter on the app.

2025-03-10 22:42 UTC, alangumer commented on src/services/bibles/transforms/chapterTransforms.ts
> +		title: chapter.title,
Only the first letter of each word is capitalized, take a look at transformBibleBrainChapter on the app.

2025-03-11 21:36 UTC, alangumer commented on src/containers/bible/chapter.tsx
> +import React, { useEffect, useRef, useState } from 'react';
The id should include the FCBH fileset id, and not the custom Bible id.

2025-03-11 21:42 UTC, alangumer commented on src/services/bibles/fcbh/fetchFcbhChapters.ts
> +			id: `${book_id}/${chapter_start}`,
The id should include the FCBH fileset id, and not the custom Bible id.

2025-03-11 21:47 UTC, alangumer commented on src/services/bibles/transforms/chapterTransforms.ts
> +		sequence: null,
When playing a chapter, the video element data attribute data-series in andMiniplayer.tsx doesn't have a value.

2025-03-13 20:37 UTC, alangumer requested changes

2025-03-13 20:37 UTC, alangumer commented on src/containers/bible/chapter/useRefreshedRecordings.graphql
> +fragment Refreshable on Recording {
Remove this because you are not using it as a GraphQL fragment but as a TS type.

2025-03-19 15:58 UTC, alangumer approved these changes

2025-03-19 16:19 UTC, merged